[unstable]
build-std = ["core", "alloc", "panic_abort"]
build-std-features = ["optimize_for_size"]

[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
rustflags = [
  "-C", "linker-plugin-lto",
  "-Z", "merge-functions=aliases",
  "-C", "link-arg=--icf=all",
  "-C", "link-arg=-O3",
  "-C", "llvm-args=-mergefunc-preserve-debug-info=false",
  "-C", "llvm-args=-mergefunc-use-aliases",
  "-C", "llvm-args=-enable-dfa-jump-thread",
]
